name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -vvv -o StrictHostKeyChecking=no -o IdentitiesOnly=yes ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            ls -la &&
            cd /home/sga-cakrawala/htdocs/cms-cakrawala &&
            rm -rf node_modules package-lock.json &&
            rm -rf dist &&
            rm -rf .strapi &&
            nvm use 22 &&
            git stash &&
            git stash clear &&
            git checkout main &&
            git pull &&
            npm install &&
            npm run build &&
            pm2 stop cms_cakrawala &&
            pm2 del cms_cakrawala &&
            npm run pm2:develop &&
            pm2 save
          "