name: Deploy to Server

on:
  push:
    branches:
      - main  # Ganti 'main' dengan branch yang Anda inginkan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_ristek
          chmod 600 ~/.ssh/id_rsa_ristek
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/sga-cakrawala/htdocs/cms-cakrawala && 
            git pull origin main &&
            npm install &&
            npm run build &&
            npm run pm2:start
          "
